### ISSUE TITLE
Joao

### ISSUE THREAD

**Issue by JoaoAndre-RosaTeixeira** [JoaoAndre-RosaTeixeira/musee_virtuel_engrenage#2]
terminate Front css of accueil, create page contact and css.

**Comment by JoaoAndre-RosaTeixeira** [comment]
front for accueil, engrenages, engrenage terminate

**Comment by JoaoAndre-RosaTeixeira** [comment]
lakhbir create page contact

**Comment by LakhbirSin** [comment]
Done
